### PR TITLE
Store servers in db

### LINKED ISSUE #28: Store GameServer info in database
## Problem
From my testing i noticed that if master server goes offline and back online, then game server does not try to reestablish connection from scratch. Instead it just continues sending heartbeats and failing because master server doesn't know it exists.

## Solution
Instead of just keeping a singleton instance of `MatchmakingService` which keeps all game server data in memory, we should store all info in database.

### PR DESCRIPTION
**Pull request by timiimit**
It wasn't properly tested as of yet, but generally should work as expected. `MatchmakingService.List` definitely requires testing.

Closes #28

### CODE REVIEW

File: UT4MasterServer/Models/GameServer.cs [hunk 1]
```diff
@@ -50,6 +52,69 @@ public void SetInternal(string key, object? value)
...
+			SetDirect(attribute.Key, attribute.Value);
+		}
+	}
+
+	public bool Contains(string key)
+	{
+		return ServerConfigs.ContainsKey(key);
+	}
+
+	public bool Eq(string key, JsonElement value)
```
Comment (Saibamen) [inline UT4MasterServer/Models/GameServer.cs:76]: Please add XML comments to `Eq`, `Lt` and `Lte` methods

File: UT4MasterServer/Models/GameServer.cs [hunk 2]
```diff
@@ -70,119 +135,131 @@ public JObject ToJObject()
...
-		IsDedicated = true;
-		UsesStats = false;
-		AllowInvites = true;
-		UsesPresence = false;
-		AllowJoinViaPresence = true;
-		AllowJoinViaPresenceFriendsOnly = false;
-		BuildUniqueID = "256652735";
-		LastUpdated = DateTimeExtension.UnixTimestampStartOfTime;
-		Started = false;
+		// everything is already initialized
```
Comment (Saibamen) [inline UT4MasterServer/Models/GameServer.cs:254]: Remove empty constructor

File: UT4MasterServer/Models/GameServer.cs (hunk 1 above)
Comment (Saibamen) [reply UT4MasterServer/Models/GameServer.cs:76]: And maybe unit tests for this?

**Review by Saibamen — CHANGES_REQUESTED** [review]

File: UT4MasterServer/Models/GameServer.cs [hunk 3]
```diff
@@ -70,119 +135,131 @@ public JObject ToJObject()
...
-	public string BuildUniqueID { get; set; }
+	public string BuildUniqueID { get; set; } = "256652735";
 
+	[BsonElement("LastUpdated")]
 	[JsonPropertyName("lastUpdated")]
-	public DateTime LastUpdated { get; set; }
+	public DateTime LastUpdated { get; set; } = DateTimeExtension.UnixTimestampStartOfTime;
 
+	/// <summary>
+	/// not sure what this is used for, perhaps we can remove it
```
Comment (Saibamen) [inline UT4MasterServer/Models/GameServer.cs:240]: Add `TODO:` for better TODO's search experience ;)

File: UT4MasterServer/Models/GameServer.cs (hunk 2 above)
Comment (timiimit) [reply UT4MasterServer/Models/GameServer.cs:254]: Because there is already another constructor the default one doesn't implicitly exist. Therefore we need to at least define it, else the other one with parameters is the only existing constructor.

**Comment by timiimit** [comment]
forgot to mention, this closes #28

File: .Tests/XUnit.Tests/GameServerAttributeTest.cs [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+	public static TheoryData<object?, bool, bool, bool> TestCasesNull = new()
+	{
+
+		{ null, true, false, true },
+		{ true, false, false, false },
+		{ 3, false, false, false },
+		{ "null", false, false, false },
+	};
+
+		[Theory]
```
Comment (Saibamen) [inline .Tests/XUnit.Tests/GameServerAttributeTest.cs:49]:
```suggestion
	[Theory]
```

**Comment by Saibamen** [comment]
> forgot to mention, this closes #28

Please edit your first message in this PR to link it to issue. Documentation: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

File: UT4MasterServer/Services/MatchmakingService.cs [hunk 5]
```diff
@@ -54,94 +51,71 @@ public bool Remove(EpicID sessionID, EpicID serverID)
...
-		RemoveStale();
+		await RemoveStale();
 
-		var matches = new List<GameServer>();
-		foreach (var server in serversBySession.Values)
-		{
-			if (!server.Started)
-				continue;
+		var filter =
+			Builders<GameServer>.Filter.Eq(x => x.Started, true);
```
Comment (Saibamen) [inline UT4MasterServer/Services/MatchmakingService.cs:65]:
```suggestion
		var filter = Builders<GameServer>.Filter.Eq(x => x.Started, true);
```

File: UT4MasterServer/Services/MatchmakingService.cs [hunk 6]
```diff
@@ -54,94 +51,71 @@ public bool Remove(EpicID sessionID, EpicID serverID)
...
-
-				if (!isConditionMet)
-				{
-					isMatch = false;
-					break;
-				}
-			}
+		//if (inputFilter.OpenPlayersRequired != null)
+		//	filter &= Builders<GameServer>.Filter.Eq(x => x.MaxPublicPlayers - x.PublicPlayers.Count, inputFilter.OpenPlayersRequired);
+
```
Comment (Saibamen) [inline UT4MasterServer/Services/MatchmakingService.cs:72]:
```suggestion
```
